name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches-ignore:
      - dev
      - staging

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Package
        run: pnpm run package

      - name: Test
        run: pnpm run test

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          milliseconds: 1000
